# Generated by Django 6.0.2 on 2026-06-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_info_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='work_exp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='work_exp_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
